### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by bryanwoods** [oggy/db_nazi#4]
@oggy I'm adding this to a new project and need to bump the activerecord version dependency. Wondered if you'd add me as an author to the gem so I could push a new version.

```
$ gem push db_nazi-0.0.6.gem 
Pushing gem to https://rubygems.org...
You do not have permission to push to this gem. Ask an owner to add you with: gem owner db_nazi --add bryanwoods4e@gmail.com
```

**Comment by oggy** [comment]
Done!
